using System.ComponentModel;
using System.Drawing;
using System.Windows.Forms;
using System.Windows.Forms.DataVisualization.Charting;
using Font = System.Drawing.Font;

namespace lab7
{
    public partial class Form1
    {
        private IContainer? components;

        private Button Start = null!;
        private Button button1 = null!;
        private Button button2 = null!;
        private Button save_button = null!;
        private System.Windows.Forms.Timer timer1 = null!;

        private NumericUpDown numericUpDown1 = null!;
        private NumericUpDown numericUpDown2 = null!;
        private NumericUpDown numericUpDown3 = null!;
        private NumericUpDown numericUpDown4 = null!;
        private NumericUpDown numericUpDown5 = null!;
        private NumericUpDown numericUpDown6 = null!;
        private NumericUpDown numericUpDown7 = null!;
        private NumericUpDown numericUpDown8 = null!;
        private NumericUpDown numericUpDown9 = null!;
        private NumericUpDown T = null!;

        private Label log_Day = null!;
        private Label label1 = null!;
        private Label label_initState = null!;
        private Label label_title = null!;
        private Label label_matHdr = null!;
        private Label label_col1 = null!;
        private Label label_col2 = null!;
        private Label label_col3 = null!;
        private Label label_row1 = null!;
        private Label label_row2 = null!;
        private Label label_row3 = null!;
        private Label label_statsHdr = null!;
        private Label label_stateHdr = null!;

        private PictureBox pictureBox1 = null!;
        private ListBox listBox1 = null!;
        private Chart chart1 = null!;

        protected override void Dispose(bool disposing)
        {
            if (disposing && components != null)
            {
                components.Dispose();
            }

            base.Dispose(disposing);
        }

        private void InitializeComponent()
        {
            components = new Container();
            ChartArea chartArea1 = new ChartArea();
            Legend legend1 = new Legend();
            Start = new Button();
            button1 = new Button();
            button2 = new Button();
            save_button = new Button();
            timer1 = new System.Windows.Forms.Timer(components);
            numericUpDown1 = new NumericUpDown();
            numericUpDown2 = new NumericUpDown();
            numericUpDown3 = new NumericUpDown();
            numericUpDown4 = new NumericUpDown();
            numericUpDown5 = new NumericUpDown();
            numericUpDown6 = new NumericUpDown();
            numericUpDown7 = new NumericUpDown();
            numericUpDown8 = new NumericUpDown();
            numericUpDown9 = new NumericUpDown();
            T = new NumericUpDown();
            log_Day = new Label();
            label1 = new Label();
            label_initState = new Label();
            label_title = new Label();
            label_matHdr = new Label();
            label_col1 = new Label();
            label_col2 = new Label();
            label_col3 = new Label();
            label_row1 = new Label();
            label_row2 = new Label();
            label_row3 = new Label();
            label_statsHdr = new Label();
            label_stateHdr = new Label();
            pictureBox1 = new PictureBox();
            listBox1 = new ListBox();
            chart1 = new Chart();
            ((ISupportInitialize)numericUpDown1).BeginInit();
            ((ISupportInitialize)numericUpDown2).BeginInit();
            ((ISupportInitialize)numericUpDown3).BeginInit();
            ((ISupportInitialize)numericUpDown4).BeginInit();
            ((ISupportInitialize)numericUpDown5).BeginInit();
            ((ISupportInitialize)numericUpDown6).BeginInit();
            ((ISupportInitialize)numericUpDown7).BeginInit();
            ((ISupportInitialize)numericUpDown8).BeginInit();
            ((ISupportInitialize)numericUpDown9).BeginInit();
            ((ISupportInitialize)T).BeginInit();
            ((ISupportInitialize)pictureBox1).BeginInit();
            ((ISupportInitialize)chart1).BeginInit();
            SuspendLayout();
            label_title.AutoSize = true;
            label_title.Font = new Font("Segoe UI", 15F, FontStyle.Bold);
            label_title.ForeColor = Color.FromArgb(13, 71, 161);
            label_title.Location = new Point(550, 15);
            label_title.Name = "label_title";
            label_title.Text = "Марковская модель погоды";
            label_matHdr.AutoSize = true;
            label_matHdr.Font = new Font("Segoe UI", 9F, FontStyle.Bold);
            label_matHdr.ForeColor = Color.FromArgb(40, 40, 40);
            label_matHdr.Location = new Point(12, 15);
            label_matHdr.Name = "label_matHdr";
            label_matHdr.Text = "Матрица Q [интенсивности, дн⁻¹]:";
            label_col1.AutoSize = true;
            label_col1.Font = new Font("Segoe UI", 8.5F, FontStyle.Bold);
            label_col1.ForeColor = Color.FromArgb(230, 119, 0);
            label_col1.Location = new Point(133, 45);
            label_col1.Name = "label_col1";
            label_col1.Text = "→ Ясно";
            label_col2.AutoSize = true;
            label_col2.Font = new Font("Segoe UI", 8.5F, FontStyle.Bold);
            label_col2.ForeColor = Color.FromArgb(21, 101, 192);
            label_col2.Location = new Point(227, 45);
            label_col2.Name = "label_col2";
            label_col2.Text = "→ Облачно";
            label_col3.AutoSize = true;
            label_col3.Font = new Font("Segoe UI", 8.5F, FontStyle.Bold);
            label_col3.ForeColor = Color.FromArgb(69, 90, 100);
            label_col3.Location = new Point(323, 45);
            label_col3.Name = "label_col3";
            label_col3.Text = "→ Пасм.";
            label_row1.AutoSize = true;
            label_row1.Font = new Font("Segoe UI", 8.5F, FontStyle.Bold);
            label_row1.ForeColor = Color.FromArgb(230, 119, 0);
            label_row1.Location = new Point(12, 85);
            label_row1.Name = "label_row1";
            label_row1.Text = "Ясно";
            label_row2.AutoSize = true;
            label_row2.Font = new Font("Segoe UI", 8.5F, FontStyle.Bold);
            label_row2.ForeColor = Color.FromArgb(21, 101, 192);
            label_row2.Location = new Point(12, 135);
            label_row2.Name = "label_row2";
            label_row2.Text = "Облачно";
            label_row3.AutoSize = true;
            label_row3.Font = new Font("Segoe UI", 8.5F, FontStyle.Bold);
            label_row3.ForeColor = Color.FromArgb(69, 90, 100);
            label_row3.Location = new Point(12, 185);
            label_row3.Name = "label_row3";
            label_row3.Text = "Пасмурно";
            numericUpDown1.BackColor = Color.FromArgb(210, 215, 220);
            numericUpDown1.DecimalPlaces = 1;
            numericUpDown1.Increment = 0.1M;
            numericUpDown1.Location = new Point(133, 80);
            numericUpDown1.Maximum = 1000;
            numericUpDown1.Minimum = -1000;
            numericUpDown1.Name = "numericUpDown1";
            numericUpDown1.Size = new Size(73, 31);
            numericUpDown1.Value = -0.4M;
            numericUpDown2.DecimalPlaces = 1;
            numericUpDown2.Increment = 0.1M;
            numericUpDown2.Location = new Point(227, 80);
            numericUpDown2.Maximum = 1000;
            numericUpDown2.Name = "numericUpDown2";
            numericUpDown2.Size = new Size(73, 31);
            numericUpDown2.Value = 0.3M;
            numericUpDown3.DecimalPlaces = 1;
            numericUpDown3.Increment = 0.1M;
            numericUpDown3.Location = new Point(323, 80);
            numericUpDown3.Maximum = 1000;
            numericUpDown3.Name = "numericUpDown3";
            numericUpDown3.Size = new Size(73, 31);
            numericUpDown3.Value = 0.1M;
            numericUpDown4.DecimalPlaces = 1;
            numericUpDown4.Increment = 0.1M;
            numericUpDown4.Location = new Point(133, 130);
            numericUpDown4.Maximum = 1000;
            numericUpDown4.Name = "numericUpDown4";
            numericUpDown4.Size = new Size(73, 31);
            numericUpDown4.Value = 0.4M;
            numericUpDown5.BackColor = Color.FromArgb(210, 215, 220);
            numericUpDown5.DecimalPlaces = 1;
            numericUpDown5.Increment = 0.1M;
            numericUpDown5.Location = new Point(227, 130);
            numericUpDown5.Maximum = 1000;
            numericUpDown5.Minimum = -1000;
            numericUpDown5.Name = "numericUpDown5";
            numericUpDown5.Size = new Size(73, 31);
            numericUpDown5.Value = -0.8M;
            numericUpDown6.DecimalPlaces = 1;
            numericUpDown6.Increment = 0.1M;
            numericUpDown6.Location = new Point(323, 130);
            numericUpDown6.Maximum = 1000;
            numericUpDown6.Name = "numericUpDown6";
            numericUpDown6.Size = new Size(73, 31);
            numericUpDown6.Value = 0.4M;
            numericUpDown7.DecimalPlaces = 1;
            numericUpDown7.Increment = 0.1M;
            numericUpDown7.Location = new Point(133, 180);
            numericUpDown7.Maximum = 1000;
            numericUpDown7.Name = "numericUpDown7";
            numericUpDown7.Size = new Size(73, 31);
            numericUpDown7.Value = 0.1M;
            numericUpDown8.DecimalPlaces = 1;
            numericUpDown8.Increment = 0.1M;
            numericUpDown8.Location = new Point(227, 180);
            numericUpDown8.Maximum = 1000;
            numericUpDown8.Name = "numericUpDown8";
            numericUpDown8.Size = new Size(73, 31);
            numericUpDown8.Value = 0.4M;
            numericUpDown9.BackColor = Color.FromArgb(210, 215, 220);
            numericUpDown9.DecimalPlaces = 1;
            numericUpDown9.Increment = 0.1M;
            numericUpDown9.Location = new Point(323, 180);
            numericUpDown9.Maximum = 1000;
            numericUpDown9.Minimum = -1000;
            numericUpDown9.Name = "numericUpDown9";
            numericUpDown9.Size = new Size(73, 31);
            numericUpDown9.Value = -0.5M;
            T.Font = new Font("Segoe UI", 10F, FontStyle.Bold);
            T.Increment = 10;
            T.Location = new Point(670, 75);
            T.Maximum = 10000;
            T.Minimum = 10;
            T.Name = "T";
            T.Size = new Size(90, 34);
            T.Value = 300;
            label1.AutoSize = true;
            label1.Font = new Font("Segoe UI", 9.5F, FontStyle.Bold);
            label1.ForeColor = Color.FromArgb(40, 40, 40);
            label1.Location = new Point(500, 80);
            label1.Name = "label1";
            label1.Text = "Период [дн.]:";
            pictureBox1.BackColor = Color.FromArgb(66, 133, 244);
            pictureBox1.Location = new Point(-1, 230);
            pictureBox1.Name = "pictureBox1";
            pictureBox1.Size = new Size(1500, 3);
            pictureBox1.TabStop = false;
            label_stateHdr.AutoSize = false;
            label_stateHdr.BackColor = Color.FromArgb(10, 55, 120);
            label_stateHdr.Font = new Font("Segoe UI", 8.5F, FontStyle.Bold);
            label_stateHdr.ForeColor = Color.White;
            label_stateHdr.Location = new Point(1304, 220);
            label_stateHdr.Name = "label_stateHdr";
            label_stateHdr.Size = new Size(126, 30);
            label_stateHdr.Text = "  Текущее состояние";
            label_stateHdr.TextAlign = ContentAlignment.MiddleLeft;
            log_Day.BackColor = Color.FromArgb(13, 71, 161);
            log_Day.Font = new Font("Segoe UI", 11F, FontStyle.Bold);
            log_Day.ForeColor = Color.White;
            log_Day.Location = new Point(1304, 255);
            log_Day.Name = "log_Day";
            log_Day.Size = new Size(126, 95);
            log_Day.Text = "—";
            log_Day.TextAlign = ContentAlignment.MiddleCenter;
            label_initState.BackColor = Color.FromArgb(21, 101, 192);
            label_initState.Font = new Font("Segoe UI", 9F);
            label_initState.ForeColor = Color.White;
            label_initState.Location = new Point(1304, 362);
            label_initState.Name = "label_initState";
            label_initState.Size = new Size(126, 90);
            label_initState.Text = "Нач. состояние:\n—";
            label_initState.TextAlign = ContentAlignment.MiddleCenter;
            Start.BackColor = Color.FromArgb(46, 125, 50);
            Start.FlatAppearance.BorderSize = 0;
            Start.FlatStyle = FlatStyle.Flat;
            Start.Font = new Font("Segoe UI", 10F, FontStyle.Bold);
            Start.ForeColor = Color.White;
            Start.Location = new Point(1304, 500);
            Start.Name = "Start";
            Start.Size = new Size(126, 48);
            Start.Text = "Старт";
            Start.UseVisualStyleBackColor = false;
            Start.Click += Start_Click;
            button1.BackColor = Color.FromArgb(230, 81, 0);
            button1.FlatAppearance.BorderSize = 0;
            button1.FlatStyle = FlatStyle.Flat;
            button1.Font = new Font("Segoe UI", 10F, FontStyle.Bold);
            button1.ForeColor = Color.White;
            button1.Location = new Point(1304, 560);
            button1.Name = "button1";
            button1.Size = new Size(126, 45);
            button1.Text = "Очистить";
            button1.UseVisualStyleBackColor = false;
            button1.Click += button1_Click;
            save_button.BackColor = Color.FromArgb(0, 105, 92);
            save_button.FlatAppearance.BorderSize = 0;
            save_button.FlatStyle = FlatStyle.Flat;
            save_button.Font = new Font("Segoe UI", 10F, FontStyle.Bold);
            save_button.ForeColor = Color.White;
            save_button.Location = new Point(1304, 620);
            save_button.Name = "save_button";
            save_button.Size = new Size(126, 45);
            save_button.Text = "Сохранить";
            save_button.UseVisualStyleBackColor = false;
            save_button.Click += save_button_Click;
            button2.BackColor = Color.FromArgb(198, 40, 40);
            button2.FlatAppearance.BorderSize = 0;
            button2.FlatStyle = FlatStyle.Flat;
            button2.Font = new Font("Segoe UI", 9F, FontStyle.Bold);
            button2.ForeColor = Color.White;
            button2.Location = new Point(1387, 12);
            button2.Name = "button2";
            button2.Size = new Size(43, 37);
            button2.Text = "X";
            button2.UseVisualStyleBackColor = false;
            button2.Click += button2_Click;
            label_statsHdr.AutoSize = false;
            label_statsHdr.BackColor = Color.FromArgb(13, 71, 161);
            label_statsHdr.Font = new Font("Segoe UI", 9.5F, FontStyle.Bold);
            label_statsHdr.ForeColor = Color.White;
            label_statsHdr.Location = new Point(14, 430);
            label_statsHdr.Name = "label_statsHdr";
            label_statsHdr.Size = new Size(520, 38);
            label_statsHdr.Text = "  Статистика и результаты";
            label_statsHdr.TextAlign = ContentAlignment.MiddleLeft;
            listBox1.BackColor = Color.FromArgb(240, 248, 255);
            listBox1.Font = new Font("Consolas", 9F);
            listBox1.FormattingEnabled = true;
            listBox1.HorizontalScrollbar = true;
            listBox1.ItemHeight = 22;
            listBox1.Location = new Point(12, 471);
            listBox1.Name = "listBox1";
            listBox1.Size = new Size(520, 334);
            chartArea1.Name = "ChartArea1";
            chart1.ChartAreas.Add(chartArea1);
            legend1.Name = "Legend1";
            chart1.Legends.Add(legend1);
            chart1.Location = new Point(550, 233);
            chart1.Name = "chart1";
            chart1.Size = new Size(740, 567);
            pictureBox1.Anchor = AnchorStyles.Top | AnchorStyles.Left | AnchorStyles.Right;
            chart1.Anchor = AnchorStyles.Top | AnchorStyles.Bottom | AnchorStyles.Left | AnchorStyles.Right;
            label_stateHdr.Anchor = AnchorStyles.Top | AnchorStyles.Right;
            log_Day.Anchor = AnchorStyles.Top | AnchorStyles.Right;
            label_initState.Anchor = AnchorStyles.Top | AnchorStyles.Right;
            Start.Anchor = AnchorStyles.Top | AnchorStyles.Right;
            button1.Anchor = AnchorStyles.Top | AnchorStyles.Right;
            save_button.Anchor = AnchorStyles.Top | AnchorStyles.Right;
            button2.Anchor = AnchorStyles.Top | AnchorStyles.Right;
            listBox1.Anchor = AnchorStyles.Top | AnchorStyles.Bottom | AnchorStyles.Left;
            label_statsHdr.Anchor = AnchorStyles.Top | AnchorStyles.Left;
            AutoScaleDimensions = new SizeF(10F, 25F);
            AutoScaleMode = AutoScaleMode.Font;
            BackColor = Color.FromArgb(224, 240, 255);
            ClientSize = new Size(1439, 830);
            FormBorderStyle = FormBorderStyle.Sizable;
            MaximizeBox = true;
            MinimumSize = new Size(1439, 830);
            Name = "Form1";
            StartPosition = FormStartPosition.CenterScreen;
            WindowState = FormWindowState.Maximized;
            Text = "Марковская модель погоды";
            Controls.Add(label_title);
            Controls.Add(label_matHdr);
            Controls.Add(label_col1);
            Controls.Add(label_col2);
            Controls.Add(label_col3);
            Controls.Add(label_row1);
            Controls.Add(label_row2);
            Controls.Add(label_row3);
            Controls.Add(numericUpDown1);
            Controls.Add(numericUpDown2);
            Controls.Add(numericUpDown3);
            Controls.Add(numericUpDown4);
            Controls.Add(numericUpDown5);
            Controls.Add(numericUpDown6);
            Controls.Add(numericUpDown7);
            Controls.Add(numericUpDown8);
            Controls.Add(numericUpDown9);
            Controls.Add(T);
            Controls.Add(label1);
            Controls.Add(label_stateHdr);
            Controls.Add(log_Day);
            Controls.Add(label_initState);
            Controls.Add(pictureBox1);
            Controls.Add(label_statsHdr);
            Controls.Add(listBox1);
            Controls.Add(chart1);
            Controls.Add(Start);
            Controls.Add(button1);
            Controls.Add(save_button);
            Controls.Add(button2);
            ((ISupportInitialize)numericUpDown1).EndInit();
            ((ISupportInitialize)numericUpDown2).EndInit();
            ((ISupportInitialize)numericUpDown3).EndInit();
            ((ISupportInitialize)numericUpDown4).EndInit();
            ((ISupportInitialize)numericUpDown5).EndInit();
            ((ISupportInitialize)numericUpDown6).EndInit();
            ((ISupportInitialize)numericUpDown7).EndInit();
            ((ISupportInitialize)numericUpDown8).EndInit();
            ((ISupportInitialize)numericUpDown9).EndInit();
            ((ISupportInitialize)T).EndInit();
            ((ISupportInitialize)pictureBox1).EndInit();
            ((ISupportInitialize)chart1).EndInit();
            ResumeLayout(false);
            PerformLayout();
        }
    }
}
